-- EcoEnergy PostgreSQL schema
-- Idempotent initialization script.
-- Safe to execute multiple times.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- Core organization structure
-- =========================================================

CREATE TABLE IF NOT EXISTS companies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    industry VARCHAR(120),
    legal_name VARCHAR(180),
    country_code VARCHAR(2),
    timezone VARCHAR(64) NOT NULL DEFAULT 'America/Santiago',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS facilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    code VARCHAR(40),
    name VARCHAR(150) NOT NULL,
    region VARCHAR(120),
    city VARCHAR(120),
    address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_facility_company_name UNIQUE (company_id, name),
    CONSTRAINT uq_facility_company_code UNIQUE (company_id, code),
    CONSTRAINT ck_facility_status CHECK (status IN ('active', 'inactive', 'maintenance'))
);

CREATE TABLE IF NOT EXISTS utility_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    default_unit VARCHAR(20) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS facility_areas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    name VARCHAR(80) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_facility_area_name UNIQUE (facility_id, name)
);

CREATE TABLE IF NOT EXISTS meters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    utility_type_id INTEGER NOT NULL REFERENCES utility_types(id) ON DELETE RESTRICT,
    area_id INTEGER REFERENCES facility_areas(id) ON DELETE SET NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    installed_at DATE,
    last_calibration_at DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_meter_facility_code UNIQUE (facility_id, code),
    CONSTRAINT ck_meter_status CHECK (status IN ('active', 'inactive', 'faulty', 'maintenance'))
);

-- =========================================================
-- Consumption and analytical data
-- =========================================================

CREATE TABLE IF NOT EXISTS monthly_consumptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    electricity_kwh DOUBLE PRECISION NOT NULL,
    water_m3 DOUBLE PRECISION NOT NULL,
    electricity_cost_usd DOUBLE PRECISION NOT NULL,
    water_cost_usd DOUBLE PRECISION NOT NULL,
    co2_avoided_ton DOUBLE PRECISION NOT NULL DEFAULT 0,
    source VARCHAR(120) NOT NULL DEFAULT 'etl',
    quality_status VARCHAR(20) NOT NULL DEFAULT 'validated',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_monthly_consumption UNIQUE (facility_id, year, month),
    CONSTRAINT ck_month_range CHECK (month >= 1 AND month <= 12),
    CONSTRAINT ck_year_range CHECK (year >= 2000 AND year <= 2100),
    CONSTRAINT ck_non_negative_consumption CHECK (
        electricity_kwh >= 0 AND water_m3 >= 0 AND
        electricity_cost_usd >= 0 AND water_cost_usd >= 0 AND
        co2_avoided_ton >= 0
    ),
    CONSTRAINT ck_quality_status CHECK (quality_status IN ('raw', 'validated', 'estimated'))
);

CREATE TABLE IF NOT EXISTS area_distributions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monthly_consumption_id INTEGER NOT NULL REFERENCES monthly_consumptions(id) ON DELETE CASCADE,
    area_name VARCHAR(80) NOT NULL,
    percentage DOUBLE PRECISION NOT NULL,
    CONSTRAINT uq_month_area UNIQUE (monthly_consumption_id, area_name),
    CONSTRAINT ck_area_distribution_percentage CHECK (percentage >= 0 AND percentage <= 100)
);

CREATE TABLE IF NOT EXISTS meter_monthly_readings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_id INTEGER NOT NULL REFERENCES meters(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    consumption_value DOUBLE PRECISION NOT NULL,
    cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_meter_month UNIQUE (meter_id, year, month),
    CONSTRAINT ck_meter_month_range CHECK (month >= 1 AND month <= 12),
    CONSTRAINT ck_meter_year_range CHECK (year >= 2000 AND year <= 2100),
    CONSTRAINT ck_meter_reading_non_negative CHECK (consumption_value >= 0 AND cost_usd >= 0)
);

CREATE TABLE IF NOT EXISTS ml_models (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    version VARCHAR(40) NOT NULL DEFAULT '1.0.0',
    algorithm VARCHAR(80) NOT NULL,
    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
    trained_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ml_model_name_version UNIQUE (name, version)
);

CREATE TABLE IF NOT EXISTS ml_predictions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope VARCHAR(50) NOT NULL DEFAULT 'global',
    utility VARCHAR(30) NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    predicted_value DOUBLE PRECISION NOT NULL,
    model_name VARCHAR(80) NOT NULL DEFAULT 'RandomForestRegressor',
    validation_mae DOUBLE PRECISION NOT NULL DEFAULT 0,
    model_id INTEGER REFERENCES ml_models(id) ON DELETE SET NULL,
    facility_id INTEGER REFERENCES facilities(id) ON DELETE SET NULL,
    confidence_score DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prediction_scope_utility_month UNIQUE (scope, utility, year, month),
    CONSTRAINT ck_prediction_month_range CHECK (month >= 1 AND month <= 12),
    CONSTRAINT ck_prediction_year_range CHECK (year >= 2000 AND year <= 2100)
);

-- =========================================================
-- Security and users (N:M relationships included)
-- =========================================================

CREATE TABLE IF NOT EXISTS app_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email CITEXT NOT NULL UNIQUE,
    full_name VARCHAR(160) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS app_user_roles (
    user_id INTEGER NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, role_id)
);

-- =========================================================
-- Alerts and governance
-- =========================================================

CREATE TABLE IF NOT EXISTS smart_alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NOT NULL,
    utility VARCHAR(30),
    year INTEGER,
    month INTEGER,
    is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    facility_id INTEGER REFERENCES facilities(id) ON DELETE SET NULL,
    monthly_consumption_id INTEGER REFERENCES monthly_consumptions(id) ON DELETE SET NULL,
    assigned_user_id INTEGER REFERENCES app_users(id) ON DELETE SET NULL,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_smart_alert_severity CHECK (severity IN ('critical', 'warning', 'info')),
    CONSTRAINT ck_smart_alert_month_range CHECK (month IS NULL OR (month >= 1 AND month <= 12)),
    CONSTRAINT ck_smart_alert_year_range CHECK (year IS NULL OR (year >= 2000 AND year <= 2100))
);

CREATE TABLE IF NOT EXISTS alert_configs (
    id INTEGER PRIMARY KEY,
    electricity_threshold_pct DOUBLE PRECISION NOT NULL DEFAULT 20.0,
    water_threshold_pct DOUBLE PRECISION NOT NULL DEFAULT 18.0,
    volatility_threshold_pct DOUBLE PRECISION NOT NULL DEFAULT 15.0,
    notify_email BOOLEAN NOT NULL DEFAULT TRUE,
    notify_in_app BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_alert_thresholds CHECK (
        electricity_threshold_pct > 0 AND
        water_threshold_pct > 0 AND
        volatility_threshold_pct > 0
    )
);

CREATE TABLE IF NOT EXISTS alert_subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    utility VARCHAR(30),
    min_severity VARCHAR(20) NOT NULL DEFAULT 'warning',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_alert_subscription UNIQUE (user_id, facility_id, utility),
    CONSTRAINT ck_min_severity CHECK (min_severity IN ('critical', 'warning', 'info'))
);

-- =========================================================
-- KPI, ETL, reporting
-- =========================================================

CREATE TABLE IF NOT EXISTS efficiency_targets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name VARCHAR(80) NOT NULL,
    target_value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(30) NOT NULL,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_efficiency_target_metric_unit UNIQUE (metric_name, unit),
    CONSTRAINT ck_efficiency_target_positive CHECK (target_value > 0)
);

CREATE TABLE IF NOT EXISTS facility_efficiency_targets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    metric_name VARCHAR(80) NOT NULL,
    target_value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(30) NOT NULL,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_facility_efficiency_target UNIQUE (facility_id, metric_name, unit),
    CONSTRAINT ck_facility_efficiency_target_positive CHECK (target_value > 0)
);

CREATE TABLE IF NOT EXISTS custom_metrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    unit VARCHAR(30) NOT NULL,
    target_value DOUBLE PRECISION NOT NULL,
    current_value DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_custom_metric_target_positive CHECK (target_value > 0),
    CONSTRAINT ck_custom_metric_current_non_negative CHECK (current_value >= 0)
);

CREATE TABLE IF NOT EXISTS custom_metric_values (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_metric_id INTEGER NOT NULL REFERENCES custom_metrics(id) ON DELETE CASCADE,
    facility_id INTEGER REFERENCES facilities(id) ON DELETE SET NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_custom_metric_value_month UNIQUE (custom_metric_id, facility_id, year, month),
    CONSTRAINT ck_custom_metric_values_month CHECK (month >= 1 AND month <= 12),
    CONSTRAINT ck_custom_metric_values_year CHECK (year >= 2000 AND year <= 2100)
);

CREATE TABLE IF NOT EXISTS etl_data_sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    source_type VARCHAR(20) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_data_source_type CHECK (source_type IN ('csv', 'api', 'manual'))
);

CREATE TABLE IF NOT EXISTS etl_jobs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_filename VARCHAR(180) NOT NULL,
    rows_processed INTEGER NOT NULL DEFAULT 0,
    rows_rejected INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'completed',
    notes TEXT,
    data_source_id INTEGER REFERENCES etl_data_sources(id) ON DELETE SET NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_etl_rows_non_negative CHECK (rows_processed >= 0 AND rows_rejected >= 0)
);

CREATE TABLE IF NOT EXISTS etl_schedules (
    id INTEGER PRIMARY KEY,
    cron_expression VARCHAR(64) NOT NULL DEFAULT '0 6 1 * *',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    data_source_id INTEGER REFERENCES etl_data_sources(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activity_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_type VARCHAR(50) NOT NULL,
    message VARCHAR(255) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    actor_user_id INTEGER REFERENCES app_users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type VARCHAR(30) NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER,
    generated_by_user_id INTEGER REFERENCES app_users(id) ON DELETE SET NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_report_type_period UNIQUE (report_type, year, month),
    CONSTRAINT ck_report_type CHECK (report_type IN ('monthly', 'quarterly', 'annual')),
    CONSTRAINT ck_report_month CHECK (month IS NULL OR (month >= 1 AND month <= 12))
);

-- =========================================================
-- Compatibility patching for pre-existing schemas
-- =========================================================

ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS legal_name VARCHAR(180),
    ADD COLUMN IF NOT EXISTS country_code VARCHAR(2),
    ADD COLUMN IF NOT EXISTS timezone VARCHAR(64) NOT NULL DEFAULT 'America/Santiago',
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE facilities
    ADD COLUMN IF NOT EXISTS code VARCHAR(40),
    ADD COLUMN IF NOT EXISTS city VARCHAR(120),
    ADD COLUMN IF NOT EXISTS address TEXT,
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE monthly_consumptions
    ADD COLUMN IF NOT EXISTS source VARCHAR(120) NOT NULL DEFAULT 'etl',
    ADD COLUMN IF NOT EXISTS quality_status VARCHAR(20) NOT NULL DEFAULT 'validated';

ALTER TABLE ml_predictions
    ADD COLUMN IF NOT EXISTS model_id INTEGER,
    ADD COLUMN IF NOT EXISTS facility_id INTEGER,
    ADD COLUMN IF NOT EXISTS confidence_score DOUBLE PRECISION;

ALTER TABLE smart_alerts
    ADD COLUMN IF NOT EXISTS facility_id INTEGER,
    ADD COLUMN IF NOT EXISTS monthly_consumption_id INTEGER,
    ADD COLUMN IF NOT EXISTS assigned_user_id INTEGER,
    ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

ALTER TABLE alert_configs
    ADD COLUMN IF NOT EXISTS notify_email BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notify_in_app BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE etl_jobs
    ADD COLUMN IF NOT EXISTS data_source_id INTEGER;

ALTER TABLE etl_schedules
    ADD COLUMN IF NOT EXISTS data_source_id INTEGER;

ALTER TABLE activity_logs
    ADD COLUMN IF NOT EXISTS actor_user_id INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_ml_predictions_model'
    ) THEN
        ALTER TABLE ml_predictions
            ADD CONSTRAINT fk_ml_predictions_model
            FOREIGN KEY (model_id) REFERENCES ml_models(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_ml_predictions_facility'
    ) THEN
        ALTER TABLE ml_predictions
            ADD CONSTRAINT fk_ml_predictions_facility
            FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_smart_alerts_facility'
    ) THEN
        ALTER TABLE smart_alerts
            ADD CONSTRAINT fk_smart_alerts_facility
            FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_smart_alerts_monthly_consumption'
    ) THEN
        ALTER TABLE smart_alerts
            ADD CONSTRAINT fk_smart_alerts_monthly_consumption
            FOREIGN KEY (monthly_consumption_id) REFERENCES monthly_consumptions(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_smart_alerts_assigned_user'
    ) THEN
        ALTER TABLE smart_alerts
            ADD CONSTRAINT fk_smart_alerts_assigned_user
            FOREIGN KEY (assigned_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_activity_logs_actor_user'
    ) THEN
        ALTER TABLE activity_logs
            ADD CONSTRAINT fk_activity_logs_actor_user
            FOREIGN KEY (actor_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_etl_jobs_data_source'
    ) THEN
        ALTER TABLE etl_jobs
            ADD CONSTRAINT fk_etl_jobs_data_source
            FOREIGN KEY (data_source_id) REFERENCES etl_data_sources(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_etl_schedules_data_source'
    ) THEN
        ALTER TABLE etl_schedules
            ADD CONSTRAINT fk_etl_schedules_data_source
            FOREIGN KEY (data_source_id) REFERENCES etl_data_sources(id) ON DELETE SET NULL;
    END IF;
END;
$$;

-- =========================================================
-- Indexes for performance
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_facilities_company ON facilities(company_id);
CREATE INDEX IF NOT EXISTS idx_facilities_status ON facilities(status);

CREATE INDEX IF NOT EXISTS idx_meters_facility ON meters(facility_id);
CREATE INDEX IF NOT EXISTS idx_meters_utility ON meters(utility_type_id);
CREATE INDEX IF NOT EXISTS idx_meters_area ON meters(area_id);

CREATE INDEX IF NOT EXISTS idx_monthly_consumptions_facility_period ON monthly_consumptions(facility_id, year, month);
CREATE INDEX IF NOT EXISTS idx_monthly_consumptions_period ON monthly_consumptions(year, month);
CREATE INDEX IF NOT EXISTS idx_monthly_consumptions_source ON monthly_consumptions(source);

CREATE INDEX IF NOT EXISTS idx_area_distributions_monthly ON area_distributions(monthly_consumption_id);
CREATE INDEX IF NOT EXISTS idx_meter_readings_meter_period ON meter_monthly_readings(meter_id, year, month);

CREATE INDEX IF NOT EXISTS idx_ml_predictions_scope_utility_period ON ml_predictions(scope, utility, year, month);
CREATE INDEX IF NOT EXISTS idx_ml_predictions_facility_period ON ml_predictions(facility_id, year, month);

CREATE INDEX IF NOT EXISTS idx_smart_alerts_open ON smart_alerts(is_resolved, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_smart_alerts_facility ON smart_alerts(facility_id, year, month);
CREATE INDEX IF NOT EXISTS idx_smart_alerts_assigned_user ON smart_alerts(assigned_user_id);

CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_etl_jobs_started_at ON etl_jobs(started_at DESC);

CREATE INDEX IF NOT EXISTS idx_custom_metric_values_period ON custom_metric_values(custom_metric_id, year, month);

-- =========================================================
-- Triggers for updated_at maintenance
-- =========================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_companies_updated_at') THEN
        CREATE TRIGGER trg_companies_updated_at
        BEFORE UPDATE ON companies
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at_timestamp();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_facilities_updated_at') THEN
        CREATE TRIGGER trg_facilities_updated_at
        BEFORE UPDATE ON facilities
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at_timestamp();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_meters_updated_at') THEN
        CREATE TRIGGER trg_meters_updated_at
        BEFORE UPDATE ON meters
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at_timestamp();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_monthly_consumptions_updated_at') THEN
        CREATE TRIGGER trg_monthly_consumptions_updated_at
        BEFORE UPDATE ON monthly_consumptions
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at_timestamp();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_app_users_updated_at') THEN
        CREATE TRIGGER trg_app_users_updated_at
        BEFORE UPDATE ON app_users
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at_timestamp();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_alert_configs_updated_at') THEN
        CREATE TRIGGER trg_alert_configs_updated_at
        BEFORE UPDATE ON alert_configs
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at_timestamp();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_etl_schedules_updated_at') THEN
        CREATE TRIGGER trg_etl_schedules_updated_at
        BEFORE UPDATE ON etl_schedules
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at_timestamp();
    END IF;
END;
$$;

-- =========================================================
-- Seed values
-- =========================================================

INSERT INTO utility_types (code, name, default_unit, description)
VALUES
    ('electricity', 'Electricidad', 'kWh', 'Consumo de energía eléctrica.'),
    ('water', 'Agua', 'm3', 'Consumo de agua.'),
    ('gas', 'Gas', 'm3', 'Consumo de gas combustible.'),
    ('steam', 'Vapor', 'kg', 'Consumo de vapor industrial.'),
    ('other', 'Otro', 'unit', 'Otro tipo de recurso.')
ON CONFLICT (code) DO NOTHING;

INSERT INTO roles (name, description)
VALUES
    ('admin', 'Administrador del sistema.'),
    ('analyst', 'Analista de datos y eficiencia.'),
    ('operator', 'Operador de carga y monitoreo.')
ON CONFLICT (name) DO NOTHING;

INSERT INTO etl_data_sources (name, source_type, description)
VALUES
    ('Carga CSV Manual', 'csv', 'Carga desde archivo CSV por interfaz web.'),
    ('Integración API Externa', 'api', 'Carga automática desde sistemas externos.'),
    ('Ingreso Manual', 'manual', 'Carga manual puntual por usuarios.')
ON CONFLICT (name) DO NOTHING;

INSERT INTO alert_configs (
    id,
    electricity_threshold_pct,
    water_threshold_pct,
    volatility_threshold_pct,
    notify_email,
    notify_in_app
)
VALUES (1, 20.0, 18.0, 15.0, TRUE, TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO etl_schedules (id, cron_expression, enabled)
VALUES (1, '0 6 1 * *', TRUE)
ON CONFLICT (id) DO NOTHING;

-- =========================================================
-- Analytical views
-- =========================================================

CREATE OR REPLACE VIEW v_company_monthly_consumption AS
SELECT
    c.id AS company_id,
    c.name AS company_name,
    mc.year,
    mc.month,
    SUM(mc.electricity_kwh) AS total_electricity_kwh,
    SUM(mc.water_m3) AS total_water_m3,
    SUM(mc.electricity_cost_usd + mc.water_cost_usd) AS total_cost_usd,
    SUM(mc.co2_avoided_ton) AS total_co2_avoided_ton
FROM companies c
JOIN facilities f ON f.company_id = c.id
JOIN monthly_consumptions mc ON mc.facility_id = f.id
GROUP BY c.id, c.name, mc.year, mc.month;

CREATE OR REPLACE VIEW v_open_alerts_by_facility AS
SELECT
    f.id AS facility_id,
    f.name AS facility_name,
    COUNT(sa.id) FILTER (WHERE sa.is_resolved = FALSE) AS open_alerts,
    COUNT(sa.id) FILTER (WHERE sa.severity = 'critical' AND sa.is_resolved = FALSE) AS critical_open_alerts
FROM facilities f
LEFT JOIN smart_alerts sa ON sa.facility_id = f.id
GROUP BY f.id, f.name;

COMMIT;
